include_guard(GLOBAL)

if (WIN32)
	if (NOT MSVC)
		set(VCPKG_DEFAULT_TRIPLET "x64-mingw-static" CACHE INTERNAL "vcpkg default triplet" FORCE)
		set(VCPKG_TARGET_TRIPLET "x64-mingw-static" CACHE INTERNAL "vcpkg target triplet" FORCE)
	elseif (MSVC)
		set(VCPKG_DEFAULT_TRIPLET "x64-windows-static-md" CACHE INTERNAL "vcpkg default triplet" FORCE)
		set(VCPKG_TARGET_TRIPLET "x64-windows-static-md" CACHE INTERNAL "vcpkg target triplet" FORCE)
	endif ()
elseif (LINUX)
	if (NOT CMAKE_CROSSCOMPILING)
		set(VCPKG_DEFAULT_TRIPLET "x64-linux" CACHE INTERNAL "vcpkg default triplet" FORCE)
		set(VCPKG_TARGET_TRIPLET "x64-linux" CACHE INTERNAL "vcpkg target triplet" FORCE)
	endif ()
else ()
	message(WARNING "-- Unable to detect the platform, using vcpkg defaults")
endif ()
